apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    labels:
        app: nginx
        some: value
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - image: nginx:1.17.6
                  name: nginx
                  ports:
                      - containerPort: 80
